#
# Copyright (C) 2021 The Android Open Source Project
# Copyright (C) 2021 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/oppo/cph1909

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_64_BIT_APPS := false

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := mt6765
TARGET_NO_BOOTLOADER := true

# MTK Hardware
BOARD_USES_MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true

# Recovery / Crypto (Kept for reference, but relinking disabled)
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
BOARD_USES_METADATA_PARTITION := true

# --- CRITICAL FIX: Disable TWRP relinking during ROM build ---
# These lines often cause the "writing to readonly directory /lib" error
# TARGET_RECOVERY_DEVICE_MODULES += ld-android
# TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += $(TARGET_OUT_SHARED_LIBRARIES)/ld-android.so

# Assert
TARGET_OTA_ASSERT_DEVICE := CPH1909

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_SYSTEM := system
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false


# Kernel
TARGET_NO_KERNEL := false
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x14f88000
BOARD_KERNEL_TAGS_OFFSET := 0x13f88000
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version 2

# Kernel Source Config
TARGET_KERNEL_SOURCE := kernel/oppo/cph1909
TARGET_KERNEL_CONFIG := oppo6765_18511_defconfig
KERNEL_TOOLCHAIN := $(android_build_top)/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin
KERNEL_TOOLCHAIN_PREFIX := aarch64-linux-android-
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
NEED_KERNEL_MODULE_SYSTEM := true

# VINTF Metadata
DEVICE_MATRIX_FILE := vendor/oppo/cph1909/compatibility_matrix.xml
DEVICE_MANIFEST_FILE := vendor/oppo/cph1909/manifest.xml
DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE := device/oppo/cph1909/framework_matrix.xml
BOARD_VNDK_VERSION := current

# Build System Hacks (Required for older trees on Android 13)
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_OUTSIDE_INCLUDE_DIRS := true
BUILD_BROKEN_PREBUILT_ELF_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
BUILD_BROKEN_VINTF_PRODUCT_COPY_FILES := true
BUILD_BROKEN_VERIFY_USES_LIBRARIES := true

# Resource/RAM Management
WITH_DEXPREOPT := false
DEX_PREOPT_DEFAULT := nostripping
USE_CCACHE := 1

# Limit parallel jobs due to 8GB RAM limit
SOONG_PARALLEL_JOBS := 1